### ISSUE TITLE
Better Biome Reblend video config not showing with Embedium installed

### ISSUE THREAD

**Issue by LaBestiaBrutal** [UntitledModGroup/better-biome-blend-reblend#2]
Just reporting that this mod video settings at the options menu is not showing when Embedium is being used, it just shows the regular 7 blocks max blending.
Thank you!
Awesome mod by the way!

**Comment by Cartrigger** [comment]
This is because I do not hook into Embeddium Forge yet, though on Fabric it should work (in this case of showing in video settings)

**Comment by Cartrigger** [comment]
I am hoping to update this project overall to sodium 5.8 soon, meaning that Embeddium Forge hooks will be possible

**Comment by DeshiDesu** [comment]
I am waiting for this update

**Comment by D313m** [comment]
Hi! Have there been any updates regarding the transition?
